// Word Study Dictionary — Hebrew (OT) and Greek (NT)
// Modeled after Strong's Concordance entries

export interface WordEntry {
  original: string;         // Hebrew or Greek text
  transliteration: string;
  pronunciation: string;
  strongsNumber?: string;   // e.g. H430, G2316
  partOfSpeech: string;
  definition: string;
  extendedDef?: string;     // deeper meaning / usage notes
  root?: string;            // root word
  rootMeaning?: string;
  occurrences?: number;     // approximate times in Scripture
  lang: 'hebrew' | 'greek';
}

// Key: lowercase English word → entry
// Some words map to multiple entries depending on context (OT vs NT)
const hebrewDict: Record<string, WordEntry> = {
  'god': { original: 'אֱלֹהִים', transliteration: 'Elohim', pronunciation: 'el-oh-HEEM', strongsNumber: 'H430', partOfSpeech: 'Noun, masculine plural', definition: 'God, gods, mighty ones — the supreme deity', extendedDef: 'Plural form suggesting majesty and fullness. Used over 2,600 times. Can refer to the one true Elohim, false gods, or mighty rulers depending on context.', root: 'אֵל (El)', rootMeaning: 'Mighty one, power, strength', occurrences: 2602, lang: 'hebrew' },
  'lord': { original: 'יְהוָה', transliteration: 'Yahweh', pronunciation: 'yah-WEH', strongsNumber: 'H3068', partOfSpeech: 'Proper noun', definition: 'The proper name of the God of Israel — "I AM WHO I AM"', extendedDef: 'The tetragrammaton YHWH. The most sacred name, appearing nearly 7,000 times. Derived from the root "hayah" — to be, to exist. Replaced with "LORD" in most translations.', root: 'הָיָה (hayah)', rootMeaning: 'To be, to exist, to become', occurrences: 6828, lang: 'hebrew' },
  'beginning': { original: 'רֵאשִׁית', transliteration: 'Reshit', pronunciation: 'ray-SHEET', strongsNumber: 'H7225', partOfSpeech: 'Noun, feminine', definition: 'Beginning, first, chief, firstfruits', extendedDef: 'From "rosh" (head). Implies the first in time, place, order, or rank. Used in Genesis 1:1 — "In the reshit, Elohim created..."', root: 'רֹאשׁ (rosh)', rootMeaning: 'Head, top, summit, chief', occurrences: 51, lang: 'hebrew' },
  'created': { original: 'בָּרָא', transliteration: 'Bara', pronunciation: 'bah-RAH', strongsNumber: 'H1254', partOfSpeech: 'Verb, Qal', definition: 'To create, to shape, to fashion — used exclusively of divine creation', extendedDef: 'Only Elohim is the subject of "bara." It implies creation from nothing or radical transformation. Distinguished from "asah" (to make) and "yatsar" (to form).', root: 'בָּרָא', rootMeaning: 'To create (divine act)', occurrences: 54, lang: 'hebrew' },
  'heaven': { original: 'שָׁמַיִם', transliteration: 'Shamayim', pronunciation: 'shah-MY-im', strongsNumber: 'H8064', partOfSpeech: 'Noun, masculine plural', definition: 'Heaven, heavens, sky', extendedDef: 'Dual/plural form — can refer to the visible sky, the celestial realm, or the dwelling place of Elohim. "The heavens declare the glory of El" (Psalm 19:1).', occurrences: 421, lang: 'hebrew' },
  'earth': { original: 'אֶרֶץ', transliteration: 'Erets', pronunciation: 'EH-rets', strongsNumber: 'H776', partOfSpeech: 'Noun, feminine', definition: 'Earth, land, ground, territory', extendedDef: 'Can mean the whole earth, a specific land (e.g., Land of Yisra\'el), or ground/soil. One of the most common nouns in the Hebrew Bible.', occurrences: 2504, lang: 'hebrew' },
  'spirit': { original: 'רוּחַ', transliteration: 'Ruach', pronunciation: 'ROO-akh', strongsNumber: 'H7307', partOfSpeech: 'Noun, feminine', definition: 'Spirit, wind, breath', extendedDef: 'Can mean wind, breath, or spirit depending on context. The Ruach of Elohim moved upon the face of the waters (Genesis 1:2). Also used for the human spirit and for attitude/disposition.', occurrences: 378, lang: 'hebrew' },
  'water': { original: 'מַיִם', transliteration: 'Mayim', pronunciation: 'MY-im', strongsNumber: 'H4325', partOfSpeech: 'Noun, masculine plural', definition: 'Water, waters', extendedDef: 'Always in plural form. Used literally (seas, rivers) and figuratively (chaos, nations, cleansing, life).', occurrences: 582, lang: 'hebrew' },
  'waters': { original: 'מַיִם', transliteration: 'Mayim', pronunciation: 'MY-im', strongsNumber: 'H4325', partOfSpeech: 'Noun, masculine plural', definition: 'Water, waters', extendedDef: 'Always in plural form. Used literally and figuratively for chaos, nations, cleansing, and life.', occurrences: 582, lang: 'hebrew' },
  'light': { original: 'אוֹר', transliteration: 'Or', pronunciation: 'OHR', strongsNumber: 'H216', partOfSpeech: 'Noun, masculine', definition: 'Light, daylight, illumination', extendedDef: 'The first thing Elohim spoke into existence. Used physically (sunlight) and spiritually (truth, Torah, salvation). "Yahweh is my light (ori) and my salvation" (Psalm 27:1).', root: 'אוֹר', rootMeaning: 'To be or become light, to shine', occurrences: 120, lang: 'hebrew' },
  'darkness': { original: 'חֹשֶׁךְ', transliteration: 'Choshek', pronunciation: 'KHO-shek', strongsNumber: 'H2822', partOfSpeech: 'Noun, masculine', definition: 'Darkness, obscurity', extendedDef: 'Physical darkness and spiritual/moral darkness. In Genesis 1:2, darkness was upon the face of the deep before Elohim spoke light into being.', occurrences: 80, lang: 'hebrew' },
  'good': { original: 'טוֹב', transliteration: 'Tov', pronunciation: 'TOHV', strongsNumber: 'H2896', partOfSpeech: 'Adjective', definition: 'Good, pleasant, agreeable, excellent', extendedDef: 'Elohim saw that it was tov — meaning complete, functioning as designed, beautiful, and in right order. Not merely "okay" but genuinely excellent.', occurrences: 559, lang: 'hebrew' },
  'said': { original: 'אָמַר', transliteration: 'Amar', pronunciation: 'ah-MAR', strongsNumber: 'H559', partOfSpeech: 'Verb, Qal', definition: 'To say, to speak, to utter, to command', extendedDef: 'The primary verb for speech in Hebrew. Elohim "amar" — He spoke, and it was. The creative power of the spoken word.', occurrences: 5308, lang: 'hebrew' },
  'day': { original: 'יוֹם', transliteration: 'Yom', pronunciation: 'YOHM', strongsNumber: 'H3117', partOfSpeech: 'Noun, masculine', definition: 'Day, time, period', extendedDef: 'Can mean a literal day (sunrise to sunset), a 24-hour period, or an undefined period of time. "The yom of Yahweh" = the great day of judgment.', occurrences: 2301, lang: 'hebrew' },
  'night': { original: 'לַיְלָה', transliteration: 'Laylah', pronunciation: 'LIE-lah', strongsNumber: 'H3915', partOfSpeech: 'Noun, masculine', definition: 'Night, nighttime', occurrences: 233, lang: 'hebrew' },
  'man': { original: 'אָדָם', transliteration: 'Adam', pronunciation: 'ah-DAHM', strongsNumber: 'H120', partOfSpeech: 'Noun, masculine', definition: 'Man, mankind, human being', extendedDef: 'Related to "adamah" (ground/earth) — man was formed from the dust of the ground. Both a generic term for humanity and the proper name of the first man.', root: 'אֲדָמָה (adamah)', rootMeaning: 'Ground, earth, soil', occurrences: 552, lang: 'hebrew' },
  'word': { original: 'דָּבָר', transliteration: 'Davar', pronunciation: 'dah-VAR', strongsNumber: 'H1697', partOfSpeech: 'Noun, masculine', definition: 'Word, matter, thing, event', extendedDef: 'In Hebrew thought, a word is not just sound — it is an active force. The "davar of Yahweh" carries power to create, heal, judge, and transform.', occurrences: 1441, lang: 'hebrew' },
  'soul': { original: 'נֶפֶשׁ', transliteration: 'Nephesh', pronunciation: 'NEH-fesh', strongsNumber: 'H5315', partOfSpeech: 'Noun, feminine', definition: 'Soul, life, living being, self, person', extendedDef: 'Not an immortal ghost — the whole living being. "Man became a living nephesh" (Gen 2:7). Includes desires, emotions, and the life-force itself.', occurrences: 753, lang: 'hebrew' },
  'heart': { original: 'לֵב', transliteration: 'Lev', pronunciation: 'LEHV', strongsNumber: 'H3820', partOfSpeech: 'Noun, masculine', definition: 'Heart, mind, inner person, will', extendedDef: 'In Hebrew thought, the heart is the seat of intellect, will, and emotion — not just feelings. "Guard your lev above all else, for from it flow the springs of life" (Prov 4:23).', occurrences: 598, lang: 'hebrew' },
  'peace': { original: 'שָׁלוֹם', transliteration: 'Shalom', pronunciation: 'shah-LOHM', strongsNumber: 'H7965', partOfSpeech: 'Noun, masculine', definition: 'Peace, completeness, wholeness, well-being, harmony', extendedDef: 'Far more than absence of conflict. Shalom means everything in right order — health, prosperity, right relationships, nothing broken, nothing missing.', root: 'שָׁלֵם (shalem)', rootMeaning: 'To be complete, to be whole, to make peace', occurrences: 236, lang: 'hebrew' },
  'law': { original: 'תּוֹרָה', transliteration: 'Torah', pronunciation: 'toh-RAH', strongsNumber: 'H8451', partOfSpeech: 'Noun, feminine', definition: 'Instruction, teaching, law, direction', extendedDef: 'From "yarah" — to shoot (an arrow), to point the way, to instruct. Torah is not legalistic rules but loving instruction from a Father. "The Torah of Yahweh is perfect, restoring the nephesh" (Psalm 19:7).', root: 'יָרָה (yarah)', rootMeaning: 'To throw, to shoot, to point, to teach', occurrences: 219, lang: 'hebrew' },
  'holy': { original: 'קָדוֹשׁ', transliteration: 'Qadosh', pronunciation: 'kah-DOHSH', strongsNumber: 'H6918', partOfSpeech: 'Adjective', definition: 'Holy, set-apart, sacred, consecrated', extendedDef: 'To be cut off from the common, separated for a special purpose. "Be qadosh, for I Yahweh your Elohim am qadosh" (Leviticus 19:2).', root: 'קָדַשׁ (qadash)', rootMeaning: 'To be set apart, to consecrate', occurrences: 116, lang: 'hebrew' },
  'righteousness': { original: 'צְדָקָה', transliteration: 'Tsedaqah', pronunciation: 'tse-dah-KAH', strongsNumber: 'H6666', partOfSpeech: 'Noun, feminine', definition: 'Righteousness, justice, rightness', extendedDef: 'Right standing, conformity to Elohim\'s standard. Includes both moral uprightness and acts of justice/charity.', root: 'צָדַק (tsadaq)', rootMeaning: 'To be righteous, to be just', occurrences: 157, lang: 'hebrew' },
  'truth': { original: 'אֱמֶת', transliteration: 'Emet', pronunciation: 'eh-MET', strongsNumber: 'H571', partOfSpeech: 'Noun, feminine', definition: 'Truth, faithfulness, reliability, stability', extendedDef: 'From "aman" — to be firm, sure, faithful. Emet is not abstract philosophy but concrete reliability. Yahweh is the Elohim of emet.', root: 'אָמַן (aman)', rootMeaning: 'To be firm, to be faithful, to believe', occurrences: 127, lang: 'hebrew' },
  'life': { original: 'חַיִּים', transliteration: 'Chayyim', pronunciation: 'khah-YEEM', strongsNumber: 'H2416', partOfSpeech: 'Noun, masculine plural', definition: 'Life, living, alive', extendedDef: 'Always plural in Hebrew — life in its fullness. "I have set before you life (chayyim) and death, blessing and cursing; therefore choose life" (Deut 30:19).', occurrences: 268, lang: 'hebrew' },
  'death': { original: 'מָוֶת', transliteration: 'Mavet', pronunciation: 'MAH-vet', strongsNumber: 'H4194', partOfSpeech: 'Noun, masculine', definition: 'Death, dying, realm of the dead', occurrences: 153, lang: 'hebrew' },
  'covenant': { original: 'בְּרִית', transliteration: 'Berit', pronunciation: 'beh-REET', strongsNumber: 'H1285', partOfSpeech: 'Noun, feminine', definition: 'Covenant, treaty, agreement, pact', extendedDef: 'A solemn binding agreement, often sealed with blood. The berit between Yahweh and His people is the foundation of the entire biblical narrative.', occurrences: 284, lang: 'hebrew' },
  'blood': { original: 'דָּם', transliteration: 'Dam', pronunciation: 'DAHM', strongsNumber: 'H1818', partOfSpeech: 'Noun, masculine', definition: 'Blood, bloodshed, blood-guilt', extendedDef: '"The life (nephesh) of the flesh is in the blood (dam)" (Lev 17:11). Blood represents life itself and is central to atonement and covenant.', occurrences: 360, lang: 'hebrew' },
  'face': { original: 'פָּנִים', transliteration: 'Panim', pronunciation: 'pah-NEEM', strongsNumber: 'H6440', partOfSpeech: 'Noun, masculine plural', definition: 'Face, presence, surface, before', extendedDef: 'Always plural — the many expressions of the face. "Seek My panim" = seek My presence. Used for the surface of things and the presence of Elohim.', occurrences: 2109, lang: 'hebrew' },
  'voice': { original: 'קוֹל', transliteration: 'Qol', pronunciation: 'KOHL', strongsNumber: 'H6963', partOfSpeech: 'Noun, masculine', definition: 'Voice, sound, noise, thunder', extendedDef: 'The qol of Yahweh is powerful and majestic (Psalm 29). Used for the voice of Elohim, human speech, and natural sounds like thunder.', occurrences: 505, lang: 'hebrew' },
  'know': { original: 'יָדַע', transliteration: 'Yada', pronunciation: 'yah-DAH', strongsNumber: 'H3045', partOfSpeech: 'Verb, Qal', definition: 'To know, to perceive, to understand, to experience', extendedDef: 'Deep experiential knowledge, not just intellectual. Includes intimate knowledge. "Be still and yada that I am Elohim" (Psalm 46:10).', occurrences: 947, lang: 'hebrew' },
  'love': { original: 'אַהֲבָה', transliteration: 'Ahavah', pronunciation: 'ah-hah-VAH', strongsNumber: 'H160', partOfSpeech: 'Noun, feminine', definition: 'Love, affection', extendedDef: 'Deep covenantal love. "You shall love (ahav) Yahweh your Elohim with all your heart" (Deut 6:5).', root: 'אָהַב (ahav)', rootMeaning: 'To love', occurrences: 40, lang: 'hebrew' },
  'fear': { original: 'יִרְאָה', transliteration: 'Yirah', pronunciation: 'yir-AH', strongsNumber: 'H3374', partOfSpeech: 'Noun, feminine', definition: 'Fear, awe, reverence, respect', extendedDef: '"The fear (yirah) of Yahweh is the beginning of wisdom" (Prov 9:10). Not terror but deep reverence and awe before the Almighty.', root: 'יָרֵא (yare)', rootMeaning: 'To fear, to be in awe, to revere', occurrences: 45, lang: 'hebrew' },
  'sin': { original: 'חַטָּאת', transliteration: 'Chattat', pronunciation: 'khat-TAHT', strongsNumber: 'H2403', partOfSpeech: 'Noun, feminine', definition: 'Sin, sin offering, offense', extendedDef: 'From "chata" — to miss the mark, like an archer missing the target. Sin is deviation from Yahweh\'s standard. Also used for the sin offering.', root: 'חָטָא (chata)', rootMeaning: 'To miss, to sin, to go wrong', occurrences: 296, lang: 'hebrew' },
  'king': { original: 'מֶלֶךְ', transliteration: 'Melek', pronunciation: 'MEH-lek', strongsNumber: 'H4428', partOfSpeech: 'Noun, masculine', definition: 'King, ruler, sovereign', occurrences: 2523, lang: 'hebrew' },
  'son': { original: 'בֵּן', transliteration: 'Ben', pronunciation: 'BEHN', strongsNumber: 'H1121', partOfSpeech: 'Noun, masculine', definition: 'Son, child, descendant, member of a group', extendedDef: 'Used for literal sons and figuratively — "sons of Yisra\'el," "son of man," "sons of light."', occurrences: 4906, lang: 'hebrew' },
  'name': { original: 'שֵׁם', transliteration: 'Shem', pronunciation: 'SHEHM', strongsNumber: 'H8034', partOfSpeech: 'Noun, masculine', definition: 'Name, reputation, character, authority', extendedDef: 'In Hebrew thought, a name reveals character and destiny. The shem of Yahweh = His nature, authority, and reputation. "Yahweh, that is My shem" (Isaiah 42:8).', occurrences: 864, lang: 'hebrew' },
  'house': { original: 'בַּיִת', transliteration: 'Bayit', pronunciation: 'BAH-yit', strongsNumber: 'H1004', partOfSpeech: 'Noun, masculine', definition: 'House, household, family, temple', extendedDef: 'Physical house, family lineage (house of David), or the temple (house of Yahweh). Bet-Lechem = house of bread.', occurrences: 2047, lang: 'hebrew' },
  'fire': { original: 'אֵשׁ', transliteration: 'Esh', pronunciation: 'EHSH', strongsNumber: 'H784', partOfSpeech: 'Noun, feminine', definition: 'Fire, flame, burning', extendedDef: 'Used for literal fire and the presence of Elohim. "Our Elohim is a consuming fire (esh)" (Deut 4:24).', occurrences: 376, lang: 'hebrew' },
  'servant': { original: 'עֶבֶד', transliteration: 'Eved', pronunciation: 'EH-ved', strongsNumber: 'H5650', partOfSpeech: 'Noun, masculine', definition: 'Servant, slave, worshipper', extendedDef: 'From "avad" — to serve, to work. Mosheh was called the eved of Yahweh. Service to Elohim is the highest calling.', occurrences: 800, lang: 'hebrew' },
  'glory': { original: 'כָּבוֹד', transliteration: 'Kavod', pronunciation: 'kah-VOHD', strongsNumber: 'H3519', partOfSpeech: 'Noun, masculine', definition: 'Glory, honor, weight, splendor', extendedDef: 'From "kaved" — to be heavy. Glory = weightiness, substance, significance. The kavod of Yahweh filled the tabernacle.', root: 'כָּבֵד (kaved)', rootMeaning: 'To be heavy, to be honored', occurrences: 200, lang: 'hebrew' },
  'firmament': { original: 'רָקִיעַ', transliteration: 'Raqia', pronunciation: 'rah-KEE-ah', strongsNumber: 'H7549', partOfSpeech: 'Noun, masculine', definition: 'Firmament, expanse, dome', extendedDef: 'From "raqa" — to spread out, to hammer out. The expanse that separates the waters above from the waters below (Genesis 1:6-8).', root: 'רָקַע (raqa)', rootMeaning: 'To spread out, to stamp, to beat', occurrences: 17, lang: 'hebrew' },
  'void': { original: 'בֹּהוּ', transliteration: 'Bohu', pronunciation: 'BOH-hoo', strongsNumber: 'H922', partOfSpeech: 'Noun, masculine', definition: 'Void, emptiness, waste', extendedDef: 'Used with "tohu" — the earth was "tohu va-vohu" (formless and void). Describes primordial chaos before Elohim brought order.', occurrences: 3, lang: 'hebrew' },
  'deep': { original: 'תְּהוֹם', transliteration: 'Tehom', pronunciation: 'teh-HOHM', strongsNumber: 'H8415', partOfSpeech: 'Noun, feminine', definition: 'Deep, abyss, primordial ocean', extendedDef: 'The cosmic deep — the primordial waters over which the Ruach of Elohim hovered. Associated with chaos and the great waters.', occurrences: 36, lang: 'hebrew' },
  'morning': { original: 'בֹּקֶר', transliteration: 'Boqer', pronunciation: 'BOH-ker', strongsNumber: 'H1242', partOfSpeech: 'Noun, masculine', definition: 'Morning, daybreak, dawn', occurrences: 213, lang: 'hebrew' },
  'evening': { original: 'עֶרֶב', transliteration: 'Erev', pronunciation: 'EH-rev', strongsNumber: 'H6153', partOfSpeech: 'Noun, masculine', definition: 'Evening, dusk, twilight', extendedDef: '"And there was erev and there was boqer — day one." The Hebrew day begins at evening (sunset).', occurrences: 134, lang: 'hebrew' },
  'called': { original: 'קָרָא', transliteration: 'Qara', pronunciation: 'kah-RAH', strongsNumber: 'H7121', partOfSpeech: 'Verb, Qal', definition: 'To call, to proclaim, to read, to name', extendedDef: 'To call out, to summon, to give a name, to read aloud. Naming in Hebrew = declaring purpose and nature.', occurrences: 739, lang: 'hebrew' },
  'made': { original: 'עָשָׂה', transliteration: 'Asah', pronunciation: 'ah-SAH', strongsNumber: 'H6213', partOfSpeech: 'Verb, Qal', definition: 'To do, to make, to accomplish, to produce', extendedDef: 'Distinguished from "bara" (create from nothing). Asah = to fashion, shape, or produce from existing material. The most common action verb in Hebrew.', occurrences: 2633, lang: 'hebrew' },
  'saw': { original: 'רָאָה', transliteration: 'Raah', pronunciation: 'rah-AH', strongsNumber: 'H7200', partOfSpeech: 'Verb, Qal', definition: 'To see, to perceive, to understand, to experience', extendedDef: 'More than physical sight — includes comprehension and evaluation. When Elohim "raah" that it was tov, He evaluated and approved His work.', occurrences: 1311, lang: 'hebrew' },
  'divided': { original: 'בָּדַל', transliteration: 'Badal', pronunciation: 'bah-DAHL', strongsNumber: 'H914', partOfSpeech: 'Verb, Hiphil', definition: 'To separate, to divide, to distinguish, to set apart', extendedDef: 'Elohim separates light from darkness, waters from waters, holy from common. This act of separation is foundational to creation and holiness.', occurrences: 42, lang: 'hebrew' },
};

const greekDict: Record<string, WordEntry> = {
  'word': { original: 'λόγος', transliteration: 'Logos', pronunciation: 'LOH-gos', strongsNumber: 'G3056', partOfSpeech: 'Noun, masculine', definition: 'Word, statement, reason, divine expression', extendedDef: '"In the beginning was the Logos" (John 1:1). Far more than a word — it is the rational principle, the divine self-expression, the creative power of Elohim made manifest.', occurrences: 330, lang: 'greek' },
  'love': { original: 'ἀγάπη', transliteration: 'Agape', pronunciation: 'ah-GAH-pay', strongsNumber: 'G26', partOfSpeech: 'Noun, feminine', definition: 'Unconditional love, divine love, selfless love', extendedDef: 'The highest form of love — sacrificial, unconditional, and chosen. Distinct from "eros" (romantic), "philia" (friendship), and "storge" (familial). "Elohim is agape" (1 John 4:8).', occurrences: 116, lang: 'greek' },
  'faith': { original: 'πίστις', transliteration: 'Pistis', pronunciation: 'PIS-tis', strongsNumber: 'G4102', partOfSpeech: 'Noun, feminine', definition: 'Faith, trust, belief, faithfulness, conviction', extendedDef: 'Not blind belief but grounded trust based on evidence and relationship. Includes both the act of trusting and the content of what is believed. "The just shall live by pistis" (Hab 2:4/Rom 1:17).', occurrences: 244, lang: 'greek' },
  'grace': { original: 'χάρις', transliteration: 'Charis', pronunciation: 'KHAH-ris', strongsNumber: 'G5485', partOfSpeech: 'Noun, feminine', definition: 'Grace, favor, kindness, gift', extendedDef: 'Unmerited favor — but not a license to sin. Charis empowers obedience. "For by charis you have been saved through pistis" (Eph 2:8).', occurrences: 156, lang: 'greek' },
  'repentance': { original: 'μετάνοια', transliteration: 'Metanoia', pronunciation: 'meh-TAH-noy-ah', strongsNumber: 'G3341', partOfSpeech: 'Noun, feminine', definition: 'Repentance, change of mind, transformation of thinking', extendedDef: 'Not just feeling sorry — a complete reversal of mind and direction. "Meta" (change) + "nous" (mind). True metanoia produces changed behavior.', occurrences: 24, lang: 'greek' },
  'sin': { original: 'ἁμαρτία', transliteration: 'Hamartia', pronunciation: 'hah-mar-TEE-ah', strongsNumber: 'G266', partOfSpeech: 'Noun, feminine', definition: 'Sin, missing the mark, error, offense', extendedDef: 'From archery — to miss the target. Sin is falling short of Elohim\'s standard (Torah). "Sin is lawlessness (anomia)" (1 John 3:4).', occurrences: 174, lang: 'greek' },
  'kingdom': { original: 'βασιλεία', transliteration: 'Basileia', pronunciation: 'bah-sih-LAY-ah', strongsNumber: 'G932', partOfSpeech: 'Noun, feminine', definition: 'Kingdom, reign, royal power, domain', extendedDef: 'The reign of Elohim — not a geographic territory but the active rule of Yahweh. "Repent, for the basileia of heaven is at hand" (Matt 4:17).', occurrences: 162, lang: 'greek' },
  'church': { original: 'ἐκκλησία', transliteration: 'Ekklesia', pronunciation: 'ek-klay-SEE-ah', strongsNumber: 'G1577', partOfSpeech: 'Noun, feminine', definition: 'Assembly, congregation, called-out ones', extendedDef: '"Ek" (out of) + "kaleo" (to call). Not a building or denomination — the called-out assembly of believers. Used in the Septuagint for the congregation of Yisra\'el.', occurrences: 115, lang: 'greek' },
  'spirit': { original: 'πνεῦμα', transliteration: 'Pneuma', pronunciation: 'PNYOO-mah', strongsNumber: 'G4151', partOfSpeech: 'Noun, neuter', definition: 'Spirit, breath, wind', extendedDef: 'Equivalent to Hebrew "ruach." Can mean the Set-apart Spirit, the human spirit, or wind/breath. "Elohim is pneuma" (John 4:24).', occurrences: 385, lang: 'greek' },
  'truth': { original: 'ἀλήθεια', transliteration: 'Aletheia', pronunciation: 'ah-LAY-thay-ah', strongsNumber: 'G225', partOfSpeech: 'Noun, feminine', definition: 'Truth, reality, sincerity', extendedDef: '"A" (not) + "letheia" (hidden/concealed). Truth = the unconcealed, the revealed reality. "You shall know the aletheia, and the aletheia shall make you free" (John 8:32).', occurrences: 109, lang: 'greek' },
  'righteousness': { original: 'δικαιοσύνη', transliteration: 'Dikaiosune', pronunciation: 'dih-kai-oh-SOO-nay', strongsNumber: 'G1343', partOfSpeech: 'Noun, feminine', definition: 'Righteousness, justice, right standing', extendedDef: 'Right standing before Elohim. Both imputed (declared righteous) and practiced (living rightly). Closely connected to Torah obedience.', occurrences: 92, lang: 'greek' },
  'salvation': { original: 'σωτηρία', transliteration: 'Soteria', pronunciation: 'so-tay-REE-ah', strongsNumber: 'G4991', partOfSpeech: 'Noun, feminine', definition: 'Salvation, deliverance, preservation, rescue', extendedDef: 'Includes physical rescue, spiritual deliverance from sin, and ultimate eternal salvation. "Work out your own soteria with fear and trembling" (Phil 2:12).', occurrences: 46, lang: 'greek' },
  'life': { original: 'ζωή', transliteration: 'Zoe', pronunciation: 'zo-AY', strongsNumber: 'G2222', partOfSpeech: 'Noun, feminine', definition: 'Life, vitality, eternal life', extendedDef: 'Distinguished from "bios" (physical existence) and "psuche" (soul-life). Zoe = the divine, abundant, eternal quality of life. "I came that they may have zoe abundantly" (John 10:10).', occurrences: 135, lang: 'greek' },
  'death': { original: 'θάνατος', transliteration: 'Thanatos', pronunciation: 'THAH-nah-tos', strongsNumber: 'G2288', partOfSpeech: 'Noun, masculine', definition: 'Death, physical or spiritual', occurrences: 120, lang: 'greek' },
  'power': { original: 'δύναμις', transliteration: 'Dunamis', pronunciation: 'DOO-nah-mis', strongsNumber: 'G1411', partOfSpeech: 'Noun, feminine', definition: 'Power, ability, might, miracle', extendedDef: 'Inherent power and ability. "You shall receive dunamis when the Set-apart Spirit comes upon you" (Acts 1:8). Root of English "dynamite."', occurrences: 120, lang: 'greek' },
  'glory': { original: 'δόξα', transliteration: 'Doxa', pronunciation: 'DOK-sah', strongsNumber: 'G1391', partOfSpeech: 'Noun, feminine', definition: 'Glory, splendor, brightness, honor', extendedDef: 'The visible manifestation of Elohim\'s character. Greek equivalent of Hebrew "kavod." The doxa of Yahweh is His revealed majesty.', occurrences: 168, lang: 'greek' },
  'lord': { original: 'κύριος', transliteration: 'Kurios', pronunciation: 'KOO-ree-os', strongsNumber: 'G2962', partOfSpeech: 'Noun, masculine', definition: 'Lord, master, sir, owner', extendedDef: 'Used for Yahweh (quoting the OT), for Yahshua as Master, and as a respectful title. In the Septuagint, Kurios translates both YHWH and Adonai.', occurrences: 748, lang: 'greek' },
  'god': { original: 'θεός', transliteration: 'Theos', pronunciation: 'theh-OS', strongsNumber: 'G2316', partOfSpeech: 'Noun, masculine', definition: 'God, deity, the supreme being', extendedDef: 'The Greek equivalent used for Elohim. "In the beginning was the Logos, and the Logos was with Theos, and the Logos was Theos" (John 1:1).', occurrences: 1343, lang: 'greek' },
  'heaven': { original: 'οὐρανός', transliteration: 'Ouranos', pronunciation: 'oo-rah-NOS', strongsNumber: 'G3772', partOfSpeech: 'Noun, masculine', definition: 'Heaven, sky, the abode of Elohim', occurrences: 284, lang: 'greek' },
  'earth': { original: 'γῆ', transliteration: 'Ge', pronunciation: 'GAY', strongsNumber: 'G1093', partOfSpeech: 'Noun, feminine', definition: 'Earth, land, ground, soil', occurrences: 252, lang: 'greek' },
  'peace': { original: 'εἰρήνη', transliteration: 'Eirene', pronunciation: 'ay-RAY-nay', strongsNumber: 'G1515', partOfSpeech: 'Noun, feminine', definition: 'Peace, harmony, tranquility, welfare', extendedDef: 'Greek equivalent of Hebrew "shalom." Inner tranquility, right relationships, and absence of conflict. "Eirene I leave with you" (John 14:27).', occurrences: 92, lang: 'greek' },
  'cross': { original: 'σταυρός', transliteration: 'Stauros', pronunciation: 'stow-ROS', strongsNumber: 'G4716', partOfSpeech: 'Noun, masculine', definition: 'Stake, cross, execution pole', extendedDef: 'Originally an upright stake or pole. The instrument of execution upon which Yahshua was put to death. "Take up your stauros and follow Me" (Matt 16:24).', occurrences: 28, lang: 'greek' },
};

export function lookupWord(word: string, testament: 'OT' | 'NT' | 'AP'): WordEntry | null {
  const cleanWord = word.toLowerCase().replace(/[^a-z]/g, '');
  if (!cleanWord) return null;

  if (testament === 'OT' || testament === 'AP') {
    if (hebrewDict[cleanWord]) return hebrewDict[cleanWord];
  }
  if (testament === 'NT') {
    if (greekDict[cleanWord]) return greekDict[cleanWord];
  }
  // Fallback: check both
  return hebrewDict[cleanWord] || greekDict[cleanWord] || null;
}

export function getAllEntries(): { hebrew: Record<string, WordEntry>; greek: Record<string, WordEntry> } {
  return { hebrew: hebrewDict, greek: greekDict };
}
